version: "3"
services:
  directus:
    image: directus/directus:10.10.5
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "brizollajr@gmail.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: 5432
      DB_USER: directus
      DB_PASSWORD: directus
      DB_DATABASE: "directus"
      WEBSOCKETS_ENABLED: "true"
      EXTENSIONS_AUTO_RELOAD: true
      
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
